### PR TITLE
[Fix] Txn related ops

### LINKED ISSUE #245: Restricted-access example has multiple errors
- The bob account should be slightly fund to opt-in for the asset
- In the teal, pragma version must be on the first line

### PR DESCRIPTION
**Pull request by ratik21**
- Support for array arguments for `txn`, `gtxn` (eg. `txn Accounts 0`, `gtxn 0 Accounts 0`)
- Fix indexing with `txna`, `gtxna` (0 index meaning the sender's address)
- Fix tests in Parser + add more tests

Closes #245 as well.

### CODE REVIEW

File: packages/runtime/test/src/parser/parser.ts [hunk 1]
```diff
@@ -394,9 +394,12 @@ describe("Parser", function () {
...
 
     it("should return correct objects for `txn`", () => {
-      const res = opcodeFromSentence(["txn", "Fee"], 1, interpreter);
-      const expected = new Txn(["Fee"], 1, interpreter);
+      let res = opcodeFromSentence(["txn", "Fee"], 1, interpreter);
+      let expected = new Txn(["Fee"], 1, interpreter);
+      assert.deepEqual(res, expected);
 
+      res = opcodeFromSentence(["txn", "Accounts", "1"], 1, interpreter);
+      expected = new Txn(["Accounts", "1"], 1, interpreter);
```
Comment (amityadav0) [inline packages/runtime/test/src/parser/parser.ts:402]: why do we need to update these tests ? aren't we testing the array part in opcode-list.ts ?
this tests was only to check if correct object us created.

File: packages/runtime/test/src/parser/parser.ts [hunk 2]
```diff
@@ -428,11 +434,19 @@ describe("Parser", function () {
...
+      let expected = new Txna(["Accounts", "0"], 1, interpreter);
+      assert.deepEqual(res, expected);
 
+      res = opcodeFromSentence(["txna", "ApplicationArgs", "2"], 1, interpreter);
+      expected = new Txna(["ApplicationArgs", "2"], 1, interpreter);
       assert.deepEqual(res, expected);
 
+      expectRuntimeError(
+        () => opcodeFromSentence(["txna", "Fee", "2"], 1, interpreter),
+        RUNTIME_ERRORS.TEAL.INVALID_OP_ARG
```
Comment (amityadav0) [inline packages/runtime/test/src/parser/parser.ts:447]: i think this test should be in opcode-list, because this tests the field. parser only parses the sentence.

File: packages/runtime/test/src/parser/parser.ts [hunk 3]
```diff
@@ -445,11 +459,19 @@ describe("Parser", function () {
...
+      let expected = new Gtxna(["1", "Accounts", "1"], 1, interpreter);
+      assert.deepEqual(res, expected);
 
+      res = opcodeFromSentence(["gtxna", "1", "ApplicationArgs", "4"], 1, interpreter);
+      expected = new Gtxna(["1", "ApplicationArgs", "4"], 1, interpreter);
       assert.deepEqual(res, expected);
 
+      expectRuntimeError(
+        () => opcodeFromSentence(["gtxna", "1", "Fee", "4"], 1, interpreter),
+        RUNTIME_ERRORS.TEAL.INVALID_OP_ARG
```
Comment (amityadav0) [inline packages/runtime/test/src/parser/parser.ts:472]: same

File: packages/runtime/test/src/parser/parser.ts (hunk 2 above)
Comment (ratik21) [reply packages/runtime/test/src/parser/parser.ts:447]: No, this should be in parser because this validation is being done in the opcode constructor. Parser returns a new opcode, so validations in constructor should be handled in the parser tests. In `opcode-list.ts`, we are testing `op.execute()`, and not `new Op(..)`.

File: packages/runtime/test/src/parser/parser.ts (hunk 1 above)
Comment (ratik21) [reply packages/runtime/test/src/parser/parser.ts:402]: This is related to `assertLen` in constructor. Since we are passing a txField of array type we should have 2 args now, otherwise 1. Hence added two tests - a) where num of args = 1 with `Fee`, and b) where num of args = 2 with `Accounts/ApplicationArgs`. So this is related to creation of object only, not execution.
In opcode-list we test the execution (where we check if correct value was pushed to stack or not)

Comment (amityadav0) [reply packages/runtime/test/src/parser/parser.ts:402]: ok

File: packages/runtime/test/src/parser/parser.ts (hunk 2 above)
Comment (amityadav0) [reply packages/runtime/test/src/parser/parser.ts:447]: ok

File: packages/runtime/src/lib/txn.ts [hunk 4]
```diff
@@ -104,20 +104,18 @@ export function txnSpecbyField (txField: string, tx: Txn, gtxns: Txn[], tealVers
...
 
-  throw new RuntimeError(RUNTIME_ERRORS.TEAL.INVALID_OP_ARG, {
-    opcode: "txna or gtxna"
-  });
+  if (txField === 'Accounts') {
+    if (idx === 0) { return parseToStackElem(tx.snd, txField) as Uint8Array; }
+    idx--; // if not sender, then reduce index by 1
+  }
+  op.checkIndexBound(idx, result, line);
+  return parseToStackElem(result[idx], txField) as Uint8Array;
```
Comment (amityadav0) [inline packages/runtime/src/lib/txn.ts:118]: are we handling `ApplicationArgs` here ?

File: packages/runtime/test/src/interpreter/opcode-list.ts [hunk 5]
```diff
@@ -1951,6 +1951,35 @@ describe("Teal Opcodes", function () {
         assert.equal(1, stack.length());
         assert.deepEqual(TXN_OBJ.apsu, stack.pop());
       });
+
+      it("should push value from accounts or args array by index", function () {
```
Comment (amityadav0) [inline packages/runtime/test/src/interpreter/opcode-list.ts:1955]: please add test for `ApplicationArgs`.

File: packages/runtime/test/src/parser/parser.ts (hunk 1 above)
Comment (amityadav0) [reply packages/runtime/test/src/parser/parser.ts:402]: please add test for `ApplicationArgs`.

File: packages/runtime/src/interpreter/opcode-list.ts [hunk 6]
```diff
@@ -1288,6 +1318,8 @@ export class Txna extends Op {
 
 // push value of a field to the stack from a transaction in the current transaction group
 // push to stack [...stack, value of field]
+// NOTE: for arg="Accounts" index 0 means sender's address, and index 1 means first address from accounts
```
Comment (amityadav0) [inline packages/runtime/src/interpreter/opcode-list.ts:1321]: add comments for application args also

File: packages/runtime/test/src/interpreter/opcode-list.ts (hunk 5 above)
Comment (ratik21) [reply packages/runtime/test/src/interpreter/opcode-list.ts:1955]: [https://github.com/scale-it/algorand-builder/pull/248/files/71ca98c1ebf4be194883bca6637fff28fc203b9e#diff-0bd11169d40e3be81fef88fe8a8e4cf0795255b19d1f4d44d615ea872a1e0e90R1977](https://github.com/scale-it/algorand-builder/pull/248/files/71ca98c1ebf4be194883bca6637fff28fc203b9e#diff-0bd11169d40e3be81fef88fe8a8e4cf0795255b19d1f4d44d615ea872a1e0e90R1977)

File: packages/runtime/src/lib/txn.ts (hunk 4 above)
Comment (ratik21) [reply packages/runtime/src/lib/txn.ts:118]: yes. For `ApplicationArgs` it's normal indexing, that's why if we have `Accounts`, we are reducing the index by 1, otherwise normal.

File: packages/runtime/src/interpreter/opcode-list.ts (hunk 6 above)
Comment (ratik21) [reply packages/runtime/src/interpreter/opcode-list.ts:1321]: For `ApplicationArgs` index 0 means 1st application arg from array. This is the normal case. Should i add a comment for this?

File: packages/runtime/test/src/parser/parser.ts (hunk 1 above)
Comment (ratik21) [reply packages/runtime/test/src/parser/parser.ts:402]: ok, it will be similar to Accounts though

File: packages/runtime/src/interpreter/opcode-list.ts (hunk 6 above)
Comment (amityadav0) [reply packages/runtime/src/interpreter/opcode-list.ts:1321]: yes, i think that will be good, because we are taking index both in application and accounts. but application args index is different

Comment (ratik21) [reply packages/runtime/src/interpreter/opcode-list.ts:1321]: ok, fair point.

**Review by amityadav0 — APPROVED** [review]
